
services:
  matomo-db:
    container_name: matomo-db
    image: mariadb:10.11
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    command: --max-allowed-packet=64MB
    restart: unless-stopped
    volumes:
      - ./volumes/matomo-db:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: ${MATOMO_DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MATOMO_DB_PASSWORD}
      MYSQL_DATABASE: ${MATOMO_DB_DATABASE}
      MYSQL_USER: ${MATOMO_DB_USER}
      MARIADB_AUTO_UPGRADE: ${MATOMO_DB_AUTO_UPGRADE}
      MARIADB_INITDB_SKIP_TZINFO: ${MATOMO_DB_INITDB_SKIP_TZINFO}
      MARIADB_DISABLE_UPGRADE_BACKUP: ${MATOMO_DB_DISABLE_UPGRADE_BACKUP}

  matomo-app:
    container_name: matomo-app
    image: matomo:fpm-alpine
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    restart: unless-stopped
    links:
      - matomo-db
    volumes:
      - ./configs/matomo-app/:/var/www/html/config:z
      - ./volumes/matomo-app/logs:/var/www/html/logs:z
      - ./volumes/matomo-app/www:/var/www/html:z
    environment:
      MATOMO_DATABASE_HOST: matomo-db
      MATOMO_DATABASE_ADAPTER: ${MATOMO_APP_ADAPTER}
      MATOMO_DATABASE_TABLES_PREFIX: ${MATOMO_APP_TABLES_PREFIX}
      MATOMO_DATABASE_USERNAME: ${MATOMO_APP_USERNAME}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
      MATOMO_DATABASE_DBNAME: ${MATOMO_APP_DBNAME}
      PHP_MEMORY_LIMIT: 2048M

  matomo-web:
    container_name: matomo-web
    image: nginx:alpine
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    restart: unless-stopped
    volumes:
      - ./volumes/matomo-app/www:/var/www/html:z,ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./configs/matomo-web/matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${MATOMO_WEB_PORT}:80

