
services:
  db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: unless-stopped
    volumes:
      - ./dbdata:/var/lib/mysql:Z
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MARIADB_AUTO_UPGRADE: ${MARIADB_AUTO_UPGRADE}
      MARIADB_INITDB_SKIP_TZINFO: ${MARIADB_INITDB_SKIP_TZINFO}
      MARIADB_DISABLE_UPGRADE_BACKUP: ${MARIADB_DISABLE_UPGRADE_BACKUP}

  app:
    image: matomo:fpm-alpine
    restart: unless-stopped
    links:
      - db
    volumes:
      - ./config:/var/www/html/config:z
      - ./logs:/var/www/html/logs:z
      - ./www:/var/www/html:z
    environment:
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_ADAPTER: ${MATOMO_DATABASE_ADAPTER}
      MATOMO_DATABASE_TABLES_PREFIX: ${MATOMO_DATABASE_TABLES_PREFIX}
      MATOMO_DATABASE_USERNAME: ${MATOMO_DATABASE_USERNAME}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
      MATOMO_DATABASE_DBNAME: ${MATOMO_DATABASE_DBNAME}
      PHP_MEMORY_LIMIT: 2048M

  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html:z,ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    ports:
      - ${MATOMO_WEB_PORT}:80

